javascripts:
  il_javascripts:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/jquery-ui-1.8.7.custom.min.js
    - public/javascripts/jquery.ui.datepicker-zh-CN.js
    - public/javascripts/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/jquery.tipswift.js
    - public/javascripts/select_org.js
    - public/javascripts/jquery-impromptu.3.1.min.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.notifyBar.js
    - public/javascripts/jquery.watermark.min.js
    - public/javascripts/jquery.cookies.2.2.0.min.js
    - public/javascripts/chart/visualize.jQuery.js
    - public/javascripts/jquery.printElement.min.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/jquery.hotkeys.js
    - public/javascripts/jquery.fixedtableheader-1-0-2.min.js
    - public/javascripts/enter2tab.js
    - public/javascripts/bill_selector.js
    - public/javascripts/application.js
  il_ie_javascripts:
    - public/javascripts/ukey.js
    - public/javascripts/chart/excanvas.js
    - public/javascripts/web_print.js
  il_ie6_javascripts:
    - public/javascripts/ie6.js

stylesheets:
  il_stylesheets:
    - public/stylesheets/web-app-theme/base.css
    - public/stylesheets/web-app-theme/themes/default/style.css
    - public/stylesheets/jquery-ui-css/ui-lightness/jquery-ui-1.8.6.custom.css
    - public/stylesheets/SexyButtons/sexybuttons.css
    - public/stylesheets/fancybox/jquery.fancybox-1.3.4.css
    - public/stylesheets/jquery.tipswift.css
    - public/stylesheets/ufd/ufd-base.css
    - public/stylesheets/ufd/plain/plain.css
    - public/stylesheets/jquery.notifyBar.css
    - public/stylesheets/chart/visualize.css
    - public/stylesheets/chart/visualize-light.css
    - public/stylesheets/web-app-theme/override.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css

  il_ie_stylesheets:
    - public/stylesheets/formtastic_ie6fixes.css
    - public/stylesheets/ie6fixes.css
